import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export const Styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#ebfafa',
    },
    btnProfile: {
      flexDirection: 'row',
      width: wp(41),
      backgroundColor: '#fff',
      height: hp(4.4),
      borderRadius: wp(2),
    },
    arrowBtn: {
      width: wp(4),
      height: hp(4),
      resizeMode: 'contain',
      alignSelf: 'center',
      marginLeft: wp(1),
    },
    optionContainer: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.2)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    selectBtn: {
      backgroundColor: '#ebfafa',
      width: wp(34),
      height: hp(17),
      borderRadius: wp(2),
      borderWidth: 1,
      borderColor: '#e8e8e8',
      margin: hp(2.5),
      justifyContent: 'center',
    },
    editViewContainer1: {
      position: 'absolute',
      top: hp(6),
      right: wp(5),
    },
    editViewContainer2: {
      position: 'absolute',
      top: hp(37),
      right: wp(2),
      justifyContent: 'center',
      alignItems: 'center',
    },
    editTextContainer: {
      alignSelf: 'center',
      marginLeft: wp(2),
      fontWeight: '400',
      fontSize: hp(1.7),
    },
    editImageView: {
      backgroundColor: '#fff',
      height: hp(30),
      width: wp(91),
      alignSelf: 'center',
      borderRadius: wp(3),
    },
    btnTxt: {
      color: 'gray',
      textAlign: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      fontWeight: '400',
      fontSize: hp(1.6),
      marginTop: hp(1),
    },
    imageBtn: {
      height: hp(5),
      width: wp(10),
      alignSelf: 'center',
      marginTop: hp(1),
    },
    uploadPhotoText: {
      color: '#fff',
      marginLeft: wp(8),
      fontWeight: '400',
      fontSize: hp(2.2),
      justifyContent: 'space-around',
    },
    uploadPhotoTextContainer: {
      backgroundColor: '#00ccff',
      height: hp(8),
      width: wp(93),
      justifyContent: 'center',
      alignSelf: 'center',
    },
    editImageButtons: {
      flexDirection: 'row',
      gap: wp(0.2),
    },
    partition: {
      width: wp(92),
      resizeMode: 'cover',
      marginTop: hp(3),
      alignSelf: 'center',
      height: hp(0.2),
    },
    infoContainer: {
      flexDirection: 'row',
      marginTop: hp(3),
      justifyContent: 'space-between',
    },
    editProfileButton: {
      flexDirection: 'row-reverse',
      marginTop: hp(0.5),
      marginBottom: hp(2),
    },
    drawerIconTxt: {
      fontSize: hp(3.1),
      // fontWeight: '700',
      alignSelf: 'center',
      fontFamily: 'Roboto-Bold',
    },
    infoTxt: {
      fontSize: hp(2),
      fontWeight: '500',
      alignSelf: 'stretch',
      marginLeft: wp(3),
    },
    infoTxt2: {
      fontSize: hp(2),
      fontWeight: '500',
      alignSelf: 'stretch',
      marginRight: wp(3),
      color: 'gray',
    },
    profileTxt: {
      color: 'gray',
      fontWeight: '500',
      fontSize: hp(2),
    },
    topNav: {
      flex: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    profileTxtContainer: {
      alignSelf: 'center',
      marginTop: hp(1),
    },
    drawerIcon: {
      tintColor: 'white',
      width: wp(10),
      height: hp(5),
      left: wp(2),
      top: hp(1),
      resizeMode: 'cover',
    },
    pencilIcon: {
      width: wp(6),
      height: hp(3),
      top: hp(0.5),
      resizeMode: 'cover',
      alignSelf: 'center',
      justifyContent: 'center',
    },
    pencilBtn: {
      width: wp(8),
      height: hp(4),
      top: hp(2),
      right: wp(2),
      borderColor: 'white',
      borderWidth: 1,
      borderRadius: wp(5),
      backgroundColor: 'white',
    },
    pencilBtn2: {
      width: wp(8),
      height: hp(4),
      top: hp(2),
      right: wp(8),
      borderColor: 'white',
      borderWidth: 2,
      borderRadius: wp(4),
      backgroundColor: 'white',
    },
    pencilIcon3: {
      width: wp(6),
      height: hp(3),
      top: hp(-0.5),
      left: wp(-1),
      resizeMode: 'cover',
      alignSelf: 'center',
      justifyContent: 'center',
    },
    profileBack: {
      height: hp(30),
      width: wp(100),
      borderBottomLeftRadius: wp(3),
      borderBottomRightRadius: wp(3),
      resizeMode: 'cover',
      overflow: 'hidden',
    },
    userProfile: {
      width: wp(30),
      height: hp(15),
      marginTop: hp(-8),
      marginLeft: wp(8),
      borderColor: 'white',
      borderRadius: wp(15),
      borderWidth: 3,
    },
    userProfileContainer2: {
      alignSelf: 'center',
      flexDirection: 'row',
    },
    allContainers: {
      flex: 1,
    },
  });