import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export const styles = StyleSheet.create({
  actInd:{
    justifyContent: 'space-around',
    color: '#000',
    size: 70,
  },
  loaderScreenContainer:{
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    backgroundColor: '#FFFFFF',
    flex: 1,
  },
  container2: {
    flexGrow: 1,
  },
  container3: {
    backgroundColor: '#000000',
    flex: 1,
  },
  container4: {
    marginLeft: wp(4),
  },
  container5: {
    backgroundColor: '#FFFFFF',
    flex: 1,
    borderTopLeftRadius: wp(5),
    borderTopRightRadius: wp(5),
  },
  createAccountContainer: {
    flexDirection: 'row',
    alignSelf: 'center',
  },
  createAccount: {
    color: '#D06F1A',
  },
  loginTxt: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: hp(2.8),
    lineHeight: hp(3.5),
  },
  llTxt: {
    color: '#FFFFFF',
    fontWeight: '400',
    fontSize: hp(1.8),
    lineHeight: hp(3.8),
    marginVertical: hp(1),
  },
  navBack: {
    width: wp(5),
    height: hp(2),
    resizeMode: 'contain',
  },
  orItemLayout: {
    width: wp(37.5),
    resizeMode:"cover",
  },
  logoIconLayout: {
    height: hp(2.8),
    width: wp(6),
    resizeMode:"cover",
  },
  imageBgIcon: {
    height: hp(34),
  },
  logoIcon: {
    width: wp(32),
    marginLeft: wp(22),
    height: hp(2.7),
    resizeMode:"cover",
  },
  topNav: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: hp(2),
    marginLeft: wp(4),
    marginTop: hp(5.6),
  },
  frame1: {
    flex: 1,
  },
  emailChild: {
    width: wp(90),
    backgroundColor: '#F9F9F9',
    borderRadius: hp(0.7),
    borderColor: '#E8E8E8',
    borderWidth: 1,
    height: hp(5),
    borderStyle: 'solid',
    marginLeft: wp(4),
    paddingLeft: wp(3),
  },
  fieldIcons: {
    top: -hp(4),
    width: wp(6),
    height: hp(3),
    left: wp(86),
    resizeMode:"cover",
  },
  pass: {
    marginTop: hp(2),
    backgroundColor: '#F9F9F9',
    borderRadius: hp(0.7),
    height: hp(5),
    width: wp(90),
    borderWidth: 1,
    borderColor: '#E8E8E8',
    borderStyle: 'solid',
    marginLeft: wp(4),
  },
  forgotPassword: {
    color: '#d06f1a',
    fontWeight: '700',
    flexDirection: 'column',
    alignSelf: 'flex-end',
    paddingRight: wp(5),
    fontSize: hp(2),
  },
  button1: {
    textTransform: 'uppercase',
    color: '#000',
    fontWeight: '700',
    textAlign: 'left',
    fontSize: hp(2),
  },
  button: {
    backgroundColor: '#f3b232',
    shadowColor: 'gray',
    height: hp(6.3),
    shadowOpacity: 0.2,
    shadowColor: '#000000',
    shadowRadius: 3,
    elevation: 20,
    shadowOffset: {
      width: -2,
      height: 4,
    },
    borderRadius: 10,
    marginTop: hp(1.5),
    marginLeft: wp(5),
    alignItems: 'center',
    justifyContent: 'center',
    width: wp(90),
  },
  orLoginWith: {
    lineHeight: hp(4),
    textAlign: 'center',
    color: 'gray',
    fontSize: hp(2),
    marginBottom: hp(1),
  },
  loginWithLayout: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flex: 1,
  },
  continueWithGoogle: {
    color: 'gray',
    marginLeft: wp(2),
    fontSize: hp(1.9),
    alignSelf: 'stretch',
  },
  button2: {
    backgroundColor: '#f9f9f9',
    marginBottom: hp(1.2),
    borderRadius: hp(1.3),
    shadowRadius: 3,
    elevation: 20,
    shadowOpacity: 0.2,
    shadowColor: '#000000',
    shadowOffset: {
      width: -2,
      height: 4,
    },
    height: hp(6.3),
    justifyContent: 'center',
    width: wp(90),
    alignSelf: 'stretch',
    padding: hp(1.8),
    flexDirection: 'row',
    alignItems: 'center',
  },
  continueWithFacebook: {
    color: '#fff',
    marginLeft: wp(2),
    fontSize: hp(1.9),
    alignSelf: 'stretch',
  },
  button3: {
    borderWidth: 1,
    borderColor: '#e8e8e8',
    backgroundColor: '#1877f2',
    shadowOpacity: 0.2,
    shadowColor: '#000000',
    shadowRadius: 3,
    elevation: 20,
    shadowOffset: {
      width: -2,
      height: 4,
    },
    height: hp(6.3),
    justifyContent: 'center',
    width: wp(90),
    marginBottom: hp(1.2),
    flexDirection: 'row',
    padding: wp(3.2),
    borderRadius: hp(1.3),
  },
  continueWithApple: {
    color: '#fff',
    marginLeft: wp(2),
    fontSize: hp(1.9),
    alignSelf: 'stretch',
  },
  button4: {
    borderWidth: 1,
    borderColor: '#e8e8e8',
    borderStyle: 'solid',
    shadowOpacity: 0.2,
    shadowColor: '#000000',
    shadowRadius: 3,
    marginBottom: hp(2),
    elevation: 20,
    shadowOffset: {
      width: -2,
      height: 4,
    },
    height: hp(6.3),
    justifyContent: 'center',
    width: wp(90),
    borderRadius: hp(1.3),
    borderRadius: hp(1.2),
    alignSelf: 'stretch',
    padding: hp(1.8),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#000',
  },
  socmedLogin: {
    left: wp('5%'),
    flex: 1,
  },
  loginOption: {
    flex: 1,
    marginTop: hp(3.6),
  },
});
