import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export const styles = StyleSheet.create({
  errorMessage:{
    color:'red',
    marginLeft:wp(2),
    fontSize:hp(1.8),
  },
  errorName:{
    color:'red',
    marginLeft:wp(2),
    fontSize:hp(1.8),
    width:wp(44)
  },
  errorMessage2:{
    color:'red',
    marginLeft:wp(2),
    fontSize:hp(1.8),
  },
  dobContainer: {
    flex: 1,
  },
  txtContainer: {
    flex: 1,
    flexDirection:'row',
  },
  dobContainer2: {
    flexDirection: 'row',
    flex: 1,
    gap: wp(2),
  },
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  container2: {
    flexGrow: 1,
  },
  frame1: {
    flex: 1,
  },
  topNav: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: hp(2.3),
    marginLeft: wp(4),
    marginBottom: hp(2),
  },
  navBack: {
    width: wp(5),
    height: hp(2),
    resizeMode: 'contain',
  },
  logoIcon: {
    width: wp(32),
    marginLeft: wp(22),
    height: hp(2.7),
    resizeMode: 'cover',
  },
  container3: {
    backgroundColor: '#FFFFFF',
    flex: 1,
    borderTopLeftRadius: wp(5),
    borderTopRightRadius: wp(5),
  },
  registerTxt: {
    color: '#000000',
    fontWeight: '700',
    fontSize: hp(3),
    lineHeight: hp(3.3),
  },
  container4: {
    marginLeft: wp(4),
    marginTop: hp(2.7),
  },
  compltFormTxt: {
    color: '#4B4F54',
    fontWeight: '400',
    fontSize: hp(1.6),
    lineHeight: hp(2),
    marginVertical: hp(1),
  },
  container5: {
    flex: 1,
    marginTop: hp(1),
    gap: hp(2.8),
    marginLeft: wp(4),
  },
  inputField: {
    width: wp(90),
    backgroundColor: '#F9F9F9',
    borderRadius: hp(0.7),
    borderColor: '#E8E8E8',
    borderWidth: 1,
    height: hp(5),
    borderStyle: 'solid',
    paddingLeft: wp(3),
    color: '#4B4F54',
    fontFamily:'Roboto-Light',
  },
  picker:{
    backgroundColor: '#F9F9F9',
    borderRadius: hp(3),
  },
  container6: {
    flexDirection: 'row',
    gap: wp(2.4),
  },
  firstName: {
    backgroundColor: '#F9F9F9',
    borderRadius: hp(0.7),
    borderColor: '#E8E8E8',
    borderWidth: 1,
    height: hp(5),
    width: wp(44),
    borderStyle: 'solid',
    paddingLeft: wp(3),
  },
  lastName: {
    backgroundColor: '#F9F9F9',
    borderRadius: hp(0.7),
    borderColor: '#E8E8E8',
    borderWidth: 1,
    height: hp(5),
    width: wp(44),
    borderStyle: 'solid',
    paddingLeft: wp(3),
  },
  passLogo: {
    height: hp(1.6),
    width: wp(5),
    right: wp(7),
    top: hp(1.5),
  },
  arrwLogo:{
    height: hp(1.1),
    width: wp(3.3),
    right: wp(6),
    top: hp(2),
  },
  warnLogo:{
    height: hp(1.2),
    width: wp(2.4),
    top: hp(0.5),
  },
  warnInst:{
   flexDirection:'row',
   gap:wp(2),
  },
  passField: {
    marginTop: hp(1.6),
    flexDirection: 'row',
  },
  passField2: {
    flexDirection: 'row',
  },
  inputField2: {
    backgroundColor: '#F9F9F9',
    borderRadius: hp(0.7),
    borderColor: '#E8E8E8',
    borderWidth: 1,
    height: hp(5),
    borderStyle: 'solid',
    paddingLeft: wp(3),
    marginTop: hp(1),
    width: wp(29),
  },
  rgstrButton: {
    backgroundColor: '#f3b232',
    shadowColor: 'gray',
    height: hp(6.3),
    shadowOpacity: 0.2,
    shadowColor: '#000000',
    shadowRadius: 3,
    elevation: 20,
    shadowOffset: {
      width: -2,
      height: 4,
    },
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    width: wp(90),
    marginBottom: hp(2),
  },
  rgstrButton1: {
    textTransform: 'uppercase',
    color: '#000',
    fontWeight: '700',
    textAlign: 'left',
    fontSize: hp(2),
  },
  pasInstTxt: {
    color: '#4B4F54',
    fontWeight: '400',
    width: wp(84),
    fontSize: hp(1.6),
    lineHeight: hp(2),
  },
  cnfrmTxt: {
    color: '#4B4F54',
    fontWeight: '400',
    width: wp(80),
    fontSize: hp(1.6),
    lineHeight: hp(2),
  },
  optionsBox:{
    width: wp(90),
    backgroundColor: '#F9F9F9',
    borderRadius: hp(0.7),
    borderColor: '#E8E8E8',
    borderWidth: 1,
    height: hp(9),
    borderStyle: 'solid',
  },
  option: {
    paddingLeft: wp(3),
    height: hp(4.5),
    padding: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
    color: '#4B4F54',
  },
});
